#
# VanishNoPacket
#   A fine choice of invisibility for the discerning server administrator.
#   https://www.kitteh.org
#
#  See documentation for details:
#  https://dev.bukkit.org/projects/vanish/pages/configuration
#
fakeannounce:
    automaticforsilentjoin: false
    join: '%p joined the game.'
    quit: '%p left the game.'
hooks:
    essentials: false
permissionsupdates:
    checkonworldchange: false
effects:
    lightning:
        count: 30

permtest: false
debug: false
soundonvanish: true
vanishedactionbarmessage: '&&3&&lYou are vanished!'
configVersionDoNotTouch: 
    SeriouslyThisWillEraseYourConfig: 6
